server:
  port: 8001
spring:
  application:
    name: first-springcloud-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/firstcloud?useSSL=false
    username: root
    password: 123456
  zipkin:
    base-url: http://localhost:9411 #zipkin的地址
  sleuth:
    sampler:
      probability: 1 #采样率值介于0~1之间，1表示全部采样

mybatis:
  mapperLocations: classpath:/mapper/*.xml
  type-aliases-package: com.entity


#向注册中心注册
eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
