server:
  port: 9527
spring:
  application:
    name: first-springcloud-gateway
  cloud:
    #网关配置
    gateway:
      routes: #路由
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名（-代表可以为数组）
          #uri: http://localhost:8001   #断言匹配后转发的地址（不经过注册中心）
          uri: lb://first-springcloud-provider #断言匹配后转发的注册中心的服务名，并且开启负载均衡（默认轮询）
          predicates: #断言
            - Path=/student/**   #路径相匹配的进行路由(不写默认全部匹配)
        - id: payment_routh2
          uri: http://localhost:8001
          predicates:
            - Path=/payment/lb/**   #断言，路径相匹配的进行路由
eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:7001/eureka