server:
  port: 8003
spring:
  application:
    name: first-springcloud-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/firstcloud?useSSL=false
    username: root
    password: 123456
eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:7001/eureka


#mybatis
mybatis:
  mapperLocations: classpath:/mapper/*.xml
  type-aliases-package: com.entity